// Generated by CoffeeScript 1.6.3
/*
Module dependencies.
*/


(function() {
  var Schema, UserSchema, crypto, mongoose, oAuthTypes, validatePresenceOf;

  mongoose = require("mongoose");

  Schema = mongoose.Schema;

  crypto = require("crypto");

  oAuthTypes = ["github", "twitter", "facebook", "google", "linkedin"];

  /*
  User Schema
  */


  UserSchema = new Schema({
    email: {
      type: String,
      "default": ""
    },
    username: {
      type: String,
      "default": ""
    },
    provider: {
      type: String,
      "default": ""
    },
    hashed_password: {
      type: String,
      "default": ""
    },
    salt: {
      type: String,
      "default": ""
    },
    authToken: {
      type: String,
      "default": ""
    },
    role: {
      type: String,
      "default": "user"
    },
    facebook: {},
    twitter: {},
    github: {},
    google: {},
    linkedin: {}
  });

  /*
  Virtuals
  */


  UserSchema.virtual("password").set(function(password) {
    this._password = password;
    this.salt = this.makeSalt();
    this.hashed_password = this.encryptPassword(password);
  }).get(function() {
    return this._password;
  });

  /*
  Validations
  */


  validatePresenceOf = function(value) {
    return value && value.length;
  };

  UserSchema.path("email").validate((function(email) {
    if (this.doesNotRequireValidation()) {
      return true;
    }
    return email.length;
  }), "Email cannot be blank");

  UserSchema.path("email").validate((function(email, fn) {
    var User;
    User = mongoose.model("User");
    if (this.doesNotRequireValidation()) {
      fn(true);
    }
    if (this.isNew || this.isModified("email")) {
      User.find({
        email: email
      }).exec(function(err, users) {
        fn(!err && users.length === 0);
      });
    } else {
      fn(true);
    }
  }), "Email already exists");

  UserSchema.path("username").validate((function(username) {
    if (this.doesNotRequireValidation()) {
      return true;
    }
    return username.length;
  }), "Username cannot be blank");

  UserSchema.path("hashed_password").validate((function(hashed_password) {
    if (this.doesNotRequireValidation()) {
      return true;
    }
    return hashed_password.length;
  }), "Password cannot be blank");

  /*
  Pre-save hook
  */


  UserSchema.pre("save", function(next) {
    if (!this.isNew) {
      return next();
    }
    if (!validatePresenceOf(this.password) && !this.doesNotRequireValidation()) {
      next(new Error("Invalid password"));
    } else {
      next();
    }
  });

  /*
  Methods
  */


  UserSchema.methods = {
    /*
    Authenticate - check if the passwords are the same
    
    @param {String} plainText
    @return {Boolean}
    @api public
    */

    authenticate: function(plainText) {
      return this.encryptPassword(plainText) === this.hashed_password;
    },
    /*
    Make salt
    
    @return {String}
    @api public
    */

    makeSalt: function() {
      return Math.round(new Date().valueOf() * Math.random()) + "";
    },
    /*
    Encrypt password
    
    @param {String} password
    @return {String}
    @api public
    */

    encryptPassword: function(password) {
      var encrypred, err;
      if (!password) {
        return "";
      }
      encrypred = void 0;
      try {
        encrypred = crypto.createHash("sha256", this.salt).update(password).digest("hex");
        return encrypred;
      } catch (_error) {
        err = _error;
        return "";
      }
    },
    /*
    Validation is not required if using OAuth
    */

    doesNotRequireValidation: function() {
      return ~oAuthTypes.indexOf(this.provider);
    }
  };

  mongoose.model("User", UserSchema);

}).call(this);
